#!/bin/bash
# @author ibaguio
# throw away changes
# reset + checkout --

FILES=$@

if [ -z "$FILES" ]; then
    GIT_ROOT_DIR=$(git rev-parse --show-toplevel)
    FILES=$(git diff --name-only --cached | tr '\n' '\0' | xargs -0 -L1 -I '$' echo $GIT_ROOT_DIR/'$')
fi

git reset HEAD $FILES
git checkout -- $FILES
